import { StyleSheet } from "react-native";
import { COLORS } from "../../../styles/Styles";

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    filterBar: { backgroundColor: "#fff", borderBottomWidth: 1, borderBottomColor: COLORS.border },
    chip:      { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: "#fff" },
    chipText:  { fontSize: 12, fontWeight: "600", color: COLORS.textMuted },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 14,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    cardTop:      { flexDirection: "row", alignItems: "center", marginBottom: 10 },
    patientName:  { fontSize: 15, fontWeight: "700", color: COLORS.text },
    doctorName:   { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    statusBadge:  { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    statusText:   { fontSize: 11, fontWeight: "700" },
    medList:      { backgroundColor: COLORS.bg, borderRadius: 8, padding: 10, marginBottom: 8 },
    medRow:       { flexDirection: "row", alignItems: "flex-start", gap: 4, marginBottom: 3 },
    medBullet:    { color: COLORS.primary, fontWeight: "700" },
    medText:      { fontSize: 13, color: COLORS.text, flex: 1 },
    moreText:     { fontSize: 12, color: COLORS.textMuted, fontStyle: "italic" },
    cardBottom:   { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
    dateText:     { fontSize: 12, color: COLORS.textMuted },
    totalText:    { fontSize: 13, fontWeight: "700", color: COLORS.primary },
    dispenseBtn:  { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: COLORS.green, borderRadius: 10, paddingVertical: 10 },
    dispenseBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },
    emptyText:    { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    detailOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
    detailBox:    { backgroundColor: "#fff", borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, maxHeight: "85%" },
    detailHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
    detailTitle:   { fontSize: 17, fontWeight: "800", color: COLORS.text },
    detailPatient: { fontSize: 15, fontWeight: "700", color: COLORS.text, marginBottom: 2 },
    detailDoctor:  { fontSize: 13, color: COLORS.textMuted, marginBottom: 2 },
    detailNotes:   { fontSize: 13, color: COLORS.textMuted, fontStyle: "italic", marginBottom: 8 },
    divider:       { height: 1, backgroundColor: COLORS.border, marginVertical: 12 },
    detailMed:     { padding: 10, backgroundColor: COLORS.bg, borderRadius: 10, marginBottom: 8 },
    detailMedName: { fontSize: 14, fontWeight: "700", color: COLORS.text, marginBottom: 4 },
    detailMedRow:  { flexDirection: "row", justifyContent: "space-between" },
    detailMedInfo: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    detailMedInstr: { fontSize: 12, color: COLORS.primary, marginTop: 4, fontStyle: "italic" },
    detailTotal:   { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 12, borderTopWidth: 1, borderTopColor: COLORS.border, marginBottom: 12 },
    detailTotalLabel: { fontSize: 14, fontWeight: "600", color: COLORS.textMuted },
    detailTotalValue: { fontSize: 18, fontWeight: "800", color: COLORS.primary },
});
