import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../../styles/Styles";

export default StyleSheet.create({
    header: {
        backgroundColor: COLORS.primaryDark,
        paddingTop: 16,
        paddingHorizontal: 20,
        paddingBottom: 20,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    headerLeft:  { flexDirection: "row", alignItems: "center" },
    headerTitle: { color: "#fff", fontSize: 20, fontWeight: "800" },
    readAllBtn: {
        backgroundColor: "rgba(255,255,255,0.15)",
        borderRadius: 20,
        paddingHorizontal: 14,
        paddingVertical: 7,
        flexDirection: "row",
        alignItems: "center",
    },
    readAllText: { color: "#fff", fontSize: 11, fontWeight: "700" },
    tabs: {
        flexDirection: "row",
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    tabItem: {
        flex: 1,
        paddingVertical: 14,
        alignItems: "center",
        borderBottomWidth: 2.5,
        borderBottomColor: "transparent",
    },
    tabActive:     { borderBottomColor: COLORS.primary },
    tabText:       { fontSize: 13, fontWeight: "600", color: COLORS.textMuted },
    tabTextActive: { color: COLORS.primary },
    unreadBadge: {
        backgroundColor: COLORS.redLight,
        borderRadius: 8,
        minWidth: 18,
        paddingHorizontal: 5,
        paddingVertical: 1,
        alignItems: "center",
    },
    unreadBadgeText: { color: "#fff", fontSize: 10, fontWeight: "700" },
    item: {
        backgroundColor: "#fff",
        flexDirection: "row",
        alignItems: "flex-start",
        padding: 14,
        paddingHorizontal: 16,
        gap: 12,
    },
    itemUnread: { backgroundColor: "#f0f7ff" },
    sep:        { height: 1, backgroundColor: COLORS.border },
    iconWrap: {
        width: 46, height: 46,
        borderRadius: 14,
        alignItems: "center", justifyContent: "center",
        flexShrink: 0,
    },
    dot: {
        position: "absolute", top: -2, right: -2,
        width: 10, height: 10, borderRadius: 5,
        backgroundColor: COLORS.redLight,
        borderWidth: 2, borderColor: "#fff",
    },
    nTitle: { fontSize: 13, fontWeight: "700", color: COLORS.text },
    nMsg:   { fontSize: 11, color: COLORS.textMuted, marginTop: 3, lineHeight: 16 },
    nTime:  { fontSize: 10, color: COLORS.textLight, marginTop: 5 },
    emptyIcon: {
        width: 88, height: 88,
        borderRadius: 24,
        backgroundColor: COLORS.primaryPale,
        alignItems: "center", justifyContent: "center",
    },

    // NotificationDetail
    detailHeader: {
        backgroundColor: COLORS.primaryDark,
        paddingTop: Platform.OS === "ios" ? 56 : 48,
        paddingBottom: 28,
        paddingHorizontal: 20,
        alignItems: "center",
    },
    detailIconWrap: {
        width: 70, height: 70, borderRadius: 20,
        alignItems: "center", justifyContent: "center",
        marginBottom: 14,
    },
    detailTitle:   { fontSize: 20, fontWeight: "800", color: "#fff", textAlign: "center" },
    detailTime:    { fontSize: 12, color: "rgba(255,255,255,0.7)", marginTop: 8 },
    detailBody: {
        margin: 16,
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 20,
        elevation: 2,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    detailMsgTitle:  { fontSize: 14, fontWeight: "700", color: COLORS.textMuted, marginBottom: 8 },
    detailMsgText:   { fontSize: 15, color: COLORS.text, lineHeight: 24 },
    detailActionBtn: {
        margin: 16,
        marginTop: 4,
        backgroundColor: COLORS.primary,
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: "center",
        elevation: 3,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    detailActionText: { color: "#fff", fontWeight: "800", fontSize: 15 },
});
