import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../../styles/Styles";

export const staffDashboardStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    header: {
        backgroundColor: COLORS.teal,
        paddingHorizontal: 20, paddingTop: 16, paddingBottom: 24,
        flexDirection: "row", alignItems: "center", justifyContent: "space-between",
    },
    greeting: { fontSize: 20, fontWeight: "800", color: "#fff" },
    dateText: { fontSize: 13, color: "rgba(255,255,255,0.8)", marginTop: 4 },
    notifBtn: {
        width: 40, height: 40, borderRadius: 20,
        backgroundColor: "rgba(255,255,255,0.15)",
        alignItems: "center", justifyContent: "center",
    },
    revenueRow:   { flexDirection: "row", margin: 16, marginBottom: 0, gap: 10 },
    revenueCard:  { flex: 1, borderRadius: 14, padding: 14 },
    revenueLabel: { fontSize: 11, color: "rgba(255,255,255,0.8)", marginTop: 6 },
    revenueValue: { fontSize: 15, fontWeight: "800", color: "#fff", marginTop: 2 },
    section:       { margin: 16, marginBottom: 0 },
    sectionHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
    sectionTitle:  { fontSize: 16, fontWeight: "700", color: COLORS.text, marginBottom: 12 },
    seeAll:        { fontSize: 13, color: COLORS.primary, fontWeight: "600" },
    statsGrid:     { gap: 10 },
    statCard: {
        backgroundColor: "#fff", borderRadius: 12, padding: 14,
        flexDirection: "row", alignItems: "center", borderLeftWidth: 4,
        elevation: 2, shadowColor: "#000", shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06, shadowRadius: 4,
    },
    statIcon:    { width: 42, height: 42, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    statValue:   { fontSize: 22, fontWeight: "800", color: COLORS.text },
    statLabel:   { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    badge:       { width: 22, height: 22, borderRadius: 11, alignItems: "center", justifyContent: "center" },
    badgeText:   { fontSize: 11, fontWeight: "800", color: "#fff" },
    actionsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    actionBtn: {
        width: "31%", backgroundColor: "#fff", borderRadius: 12, padding: 14,
        alignItems: "center", elevation: 2,
        shadowColor: "#000", shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06, shadowRadius: 4,
    },
    actionIcon:  { width: 48, height: 48, borderRadius: 12, alignItems: "center", justifyContent: "center", marginBottom: 8 },
    actionLabel: { fontSize: 11, fontWeight: "600", color: COLORS.text, textAlign: "center" },
    apptItem: {
        backgroundColor: "#fff", borderRadius: 12, padding: 12,
        flexDirection: "row", alignItems: "center", marginBottom: 8, elevation: 1, gap: 10,
    },
    timeBox:     { padding: 8, borderRadius: 8, alignItems: "center", minWidth: 56 },
    timeText:    { fontSize: 13, fontWeight: "700", color: COLORS.primary },
    apptName:    { fontSize: 14, fontWeight: "700", color: COLORS.text },
    apptDoctor:  { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    statusText:  { fontSize: 10, fontWeight: "700" },
});

export const staffPaymentStyles = StyleSheet.create({
    summaryBanner: {
        flexDirection: "row", backgroundColor: COLORS.orange,
        paddingVertical: 14, paddingHorizontal: 24,
        justifyContent: "space-around", alignItems: "center",
    },
    summaryItem:    { alignItems: "center" },
    summaryValue:   { fontSize: 20, fontWeight: "800", color: "#fff" },
    summaryLabel:   { fontSize: 12, color: "rgba(255,255,255,0.85)", marginTop: 2 },
    summaryDivider: { width: 1, height: 36, backgroundColor: "rgba(255,255,255,0.4)" },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 14,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    cardTop:     { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    patientName: { fontSize: 15, fontWeight: "700", color: COLORS.text },
    methodText:  { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    statusText:  { fontSize: 11, fontWeight: "700" },
    amountRow:   { flexDirection: "row", alignItems: "center", marginBottom: 4 },
    amountLabel: { fontSize: 13, color: COLORS.textMuted, marginRight: 6 },
    amountValue: { fontSize: 16, fontWeight: "800", color: COLORS.primary },
    dateText:    { fontSize: 12, color: COLORS.textLight, marginBottom: 10 },
    collectBtn: {
        flexDirection: "row", alignItems: "center", justifyContent: "center",
        gap: 8, backgroundColor: COLORS.orange, borderRadius: 10, paddingVertical: 10,
    },
    collectBtnText:   { color: "#fff", fontSize: 14, fontWeight: "700" },
    emptyText:        { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    collectContainer: { flex: 1, backgroundColor: COLORS.bg },
    amountDisplay: {
        backgroundColor: COLORS.green, paddingTop: Platform.OS === "ios" ? 56 : 48,
        paddingBottom: 32, alignItems: "center",
    },
    collectLabel:      { fontSize: 14, color: "rgba(255,255,255,0.8)" },
    collectAmount:     { fontSize: 38, fontWeight: "900", color: "#fff", marginVertical: 6 },
    collectPatient:    { fontSize: 16, color: "rgba(255,255,255,0.9)", fontWeight: "600" },
    collectCard:       { margin: 16, backgroundColor: "#fff", borderRadius: 16, padding: 20, elevation: 3 },
    collectCardTitle:  { fontSize: 16, fontWeight: "700", color: COLORS.text, marginBottom: 16 },
    infoRow:   { flexDirection: "row", alignItems: "center", marginBottom: 10, gap: 8 },
    infoLabel: { fontSize: 13, color: COLORS.textMuted, flex: 1 },
    infoValue: { fontSize: 13, fontWeight: "600", color: COLORS.text },
    noteLabel: { fontSize: 13, color: COLORS.textMuted, marginTop: 12, marginBottom: 6 },
    noteInput: {
        borderWidth: 1.5, borderColor: COLORS.border,
        borderRadius: 8, padding: 10,
        fontSize: 14, color: COLORS.text, marginBottom: 16,
    },
    steps:      { backgroundColor: COLORS.greenPale, borderRadius: 10, padding: 12, marginBottom: 20 },
    stepRow:    { flexDirection: "row", alignItems: "flex-start", gap: 8, marginBottom: 8 },
    stepText:   { fontSize: 13, color: COLORS.text, flex: 1 },
    confirmBtn: { borderRadius: 10, marginBottom: 4 },
});

export const staffAppointmentDetailStyles = StyleSheet.create({
    container:         { flex: 1, backgroundColor: COLORS.bg },
    statusBanner:      { padding: 20, alignItems: "center" },
    statusBannerLabel: { fontSize: 18, fontWeight: "800", color: "#fff" },
    statusBannerDate:  { fontSize: 13, color: "rgba(255,255,255,0.85)", marginTop: 4 },
    card: {
        margin: 12, marginBottom: 0, backgroundColor: "#fff",
        borderRadius: 14, padding: 16,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.06, shadowRadius: 4,
    },
    cardTitle:    { fontSize: 13, fontWeight: "700", color: COLORS.textMuted, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 12 },
    infoRow:      { flexDirection: "row", alignItems: "flex-start", marginBottom: 8 },
    infoLabel:    { fontSize: 13, color: COLORS.textMuted, marginLeft: 6, minWidth: 90 },
    infoValue:    { fontSize: 13, color: COLORS.text, flex: 1, fontWeight: "500" },
    services:     { marginTop: 6, paddingTop: 6, borderTopWidth: 1, borderTopColor: COLORS.border },
    serviceTitle: { fontSize: 12, color: COLORS.textMuted, marginBottom: 4 },
    serviceRow:   { flexDirection: "row", justifyContent: "space-between", paddingVertical: 3 },
    serviceName:  { fontSize: 13, color: COLORS.text },
    servicePrice: { fontSize: 13, fontWeight: "600", color: COLORS.primary },
    actions:      { margin: 12, gap: 10 },
    btn:          { borderRadius: 10, paddingVertical: 4 },
});

export const staffFindPatientStyles = StyleSheet.create({
    container:   { flex: 1, backgroundColor: COLORS.bg },
    searchBox:   { backgroundColor: "#fff", padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    searchInput: { backgroundColor: COLORS.bg, elevation: 0 },
    hint:        { fontSize: 12, color: COLORS.textLight, marginTop: 4, marginLeft: 4 },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 14,
        flexDirection: "row", alignItems: "center", gap: 12,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    avatar:      { width: 48, height: 48, borderRadius: 24, backgroundColor: COLORS.primaryPale, alignItems: "center", justifyContent: "center" },
    avatarText:  { fontSize: 20, fontWeight: "800", color: COLORS.primary },
    patientName: { fontSize: 15, fontWeight: "700", color: COLORS.text, marginBottom: 2 },
    infoRow:     { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
    infoText:    { fontSize: 12, color: COLORS.textMuted },
    emptyText:   { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    modalOverlay: {
        position: "absolute", top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end",
    },
    modalBox:         { backgroundColor: "#fff", borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: "85%" },
    modalHeader:      { flexDirection: "row", alignItems: "center", marginBottom: 16, gap: 12 },
    modalAvatar:      { width: 52, height: 52, borderRadius: 26, backgroundColor: COLORS.primaryPale, alignItems: "center", justifyContent: "center" },
    modalAvatarText:  { fontSize: 22, fontWeight: "800", color: COLORS.primary },
    modalName:        { fontSize: 17, fontWeight: "800", color: COLORS.text },
    modalEmail:       { fontSize: 13, color: COLORS.textMuted, marginTop: 2 },
    patientInfo:      { backgroundColor: COLORS.bg, borderRadius: 10, padding: 12, marginBottom: 14 },
    patientInfoRow:   { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 6 },
    patientInfoLabel: { fontSize: 12, color: COLORS.textMuted, minWidth: 80 },
    patientInfoValue: { fontSize: 13, color: COLORS.text, fontWeight: "500", flex: 1 },
    historyTitle:     { fontSize: 14, fontWeight: "700", color: COLORS.text, marginBottom: 10 },
    apptRow:          { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    apptDot:          { width: 10, height: 10, borderRadius: 5 },
    apptDate:         { fontSize: 13, fontWeight: "600", color: COLORS.text },
    apptStatus:       { fontSize: 11, fontWeight: "600", marginTop: 2 },
    emptyAppt:        { color: COLORS.textMuted, textAlign: "center", paddingVertical: 12 },
});

export const staffInventoryStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    tabBar: {
        backgroundColor: "#fff",
        borderBottomWidth: 1, borderBottomColor: COLORS.border,
        flexDirection: "row", alignItems: "center",
    },
    tab: {
        flexDirection: "row", alignItems: "center", gap: 5,
        paddingHorizontal: 12, paddingVertical: 7,
        borderRadius: 20, borderWidth: 1.5, borderColor: COLORS.border,
        backgroundColor: "#fff",
    },
    tabActive:     { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
    tabText:       { fontSize: 12, fontWeight: "600", color: COLORS.textMuted },
    importBtn:     { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 12, paddingVertical: 8, marginRight: 10, borderRadius: 10, borderWidth: 1.5, borderColor: COLORS.primary },
    importBtnText: { fontSize: 12, fontWeight: "700", color: COLORS.primary },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 12,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    cardTop:        { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    medicineName:   { fontSize: 14, fontWeight: "700", color: COLORS.text },
    medicineCode:   { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    qtyBadge:       { alignItems: "center", padding: 8, borderRadius: 10, minWidth: 60 },
    qtyText:        { fontSize: 20, fontWeight: "800" },
    qtyLabel:       { fontSize: 10, color: COLORS.textMuted },
    infoRow:        { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 3 },
    infoText:       { fontSize: 12, color: COLORS.textMuted, flex: 1 },
    warningBadge:   { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 8, padding: 8, marginTop: 6 },
    warningText:    { fontSize: 12, fontWeight: "600", flex: 1 },
    alertTypeBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, alignSelf: "flex-start", marginTop: 3 },
    alertTypeText:  { fontSize: 11, fontWeight: "700" },
    resolveBtn:     { padding: 6, borderRadius: 8, backgroundColor: COLORS.greenPale },
    alertMsg:       { fontSize: 13, color: COLORS.text, marginTop: 4, marginBottom: 4 },
    dateText:       { fontSize: 12, color: COLORS.textLight },
    emptyText:      { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    modalHeader:    { backgroundColor: COLORS.primaryDark, paddingTop: 52, paddingHorizontal: 16, paddingBottom: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    modalTitle:     { fontSize: 17, fontWeight: "700", color: "#fff" },
    fieldLabel:     { fontSize: 13, fontWeight: "600", color: COLORS.text, marginBottom: 6 },
    picker:         { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderWidth: 1.5, borderColor: COLORS.border, borderRadius: 8, padding: 13, backgroundColor: "#fff", marginBottom: 12 },
    dropdown:       { borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, backgroundColor: "#fff", marginBottom: 10, overflow: "hidden" },
    dropdownItem:   { padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    dropdownText:   { fontSize: 14, fontWeight: "600", color: COLORS.text },
    dropdownSub:    { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    input:          { backgroundColor: "#fff", marginBottom: 10 },
    row:            { flexDirection: "row", gap: 10 },
});

export const staffPrescriptionsStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    filterBar: { backgroundColor: "#fff", borderBottomWidth: 1, borderBottomColor: COLORS.border },
    chip:      { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: "#fff" },
    chipText:  { fontSize: 12, fontWeight: "600", color: COLORS.textMuted },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 14,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    cardTop:      { flexDirection: "row", alignItems: "center", marginBottom: 10 },
    patientName:  { fontSize: 15, fontWeight: "700", color: COLORS.text },
    doctorName:   { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    statusBadge:  { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    statusText:   { fontSize: 11, fontWeight: "700" },
    medList:      { backgroundColor: COLORS.bg, borderRadius: 8, padding: 10, marginBottom: 8 },
    medRow:       { flexDirection: "row", alignItems: "flex-start", gap: 4, marginBottom: 3 },
    medBullet:    { color: COLORS.primary, fontWeight: "700" },
    medText:      { fontSize: 13, color: COLORS.text, flex: 1 },
    moreText:     { fontSize: 12, color: COLORS.textMuted, fontStyle: "italic" },
    cardBottom:   { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 10 },
    dateText:     { fontSize: 12, color: COLORS.textMuted },
    totalText:    { fontSize: 13, fontWeight: "700", color: COLORS.primary },
    dispenseBtn:  { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8, backgroundColor: COLORS.green, borderRadius: 10, paddingVertical: 10 },
    dispenseBtnText: { color: "#fff", fontSize: 14, fontWeight: "700" },
    emptyText:    { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    detailOverlay: { position: "absolute", top: 0, left: 0, right: 0, bottom: 0, backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end" },
    detailBox:    { backgroundColor: "#fff", borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, maxHeight: "85%" },
    detailHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
    detailTitle:   { fontSize: 17, fontWeight: "800", color: COLORS.text },
    detailPatient: { fontSize: 15, fontWeight: "700", color: COLORS.text, marginBottom: 2 },
    detailDoctor:  { fontSize: 13, color: COLORS.textMuted, marginBottom: 2 },
    detailNotes:   { fontSize: 13, color: COLORS.textMuted, fontStyle: "italic", marginBottom: 8 },
    divider:       { height: 1, backgroundColor: COLORS.border, marginVertical: 12 },
    detailMed:     { padding: 10, backgroundColor: COLORS.bg, borderRadius: 10, marginBottom: 8 },
    detailMedName: { fontSize: 14, fontWeight: "700", color: COLORS.text, marginBottom: 4 },
    detailMedRow:  { flexDirection: "row", justifyContent: "space-between" },
    detailMedInfo: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    detailMedInstr: { fontSize: 12, color: COLORS.primary, marginTop: 4, fontStyle: "italic" },
    detailTotal:   { flexDirection: "row", justifyContent: "space-between", alignItems: "center", paddingVertical: 12, borderTopWidth: 1, borderTopColor: COLORS.border, marginBottom: 12 },
    detailTotalLabel: { fontSize: 14, fontWeight: "600", color: COLORS.textMuted },
    detailTotalValue: { fontSize: 18, fontWeight: "800", color: COLORS.primary },
});

export const staffTestResultsStyles = StyleSheet.create({
    tabRow: {
        flexDirection: "row", backgroundColor: "#fff",
        paddingHorizontal: 16, paddingVertical: 10, gap: 10,
        borderBottomWidth: 1, borderBottomColor: COLORS.border,
        elevation: 2,
    },
    tabBtn:       { flex: 1, flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, paddingVertical: 8, borderRadius: 10, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: "#fff" },
    tabBtnActive: { backgroundColor: COLORS.orange, borderColor: COLORS.orange },
    tabBtnText:   { fontSize: 13, fontWeight: "700", color: COLORS.textMuted },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 14,
        elevation: 2,
        shadowColor: "#000", shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06, shadowRadius: 4,
    },
    cardTop:     { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    iconBox:     { width: 44, height: 44, borderRadius: 12, alignItems: "center", justifyContent: "center" },
    testName:    { fontSize: 15, fontWeight: "700", color: COLORS.text },
    typeLabel:   { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    statusBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 8, borderWidth: 1 },
    statusText:  { fontSize: 11, fontWeight: "700" },
    infoRow:     { flexDirection: "row", alignItems: "center", gap: 6, marginTop: 4 },
    infoText:    { fontSize: 12, color: COLORS.textMuted },
    resultBox:   { backgroundColor: COLORS.greenPale, borderRadius: 8, padding: 10, marginTop: 8, borderWidth: 1, borderColor: COLORS.green },
    resultLabel: { fontSize: 11, color: COLORS.green, fontWeight: "700", marginBottom: 2 },
    resultValue: { fontSize: 14, fontWeight: "600", color: COLORS.text },
    refText:     { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    fillBtn:     { flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 6, marginTop: 10, paddingVertical: 9, borderRadius: 10, backgroundColor: COLORS.primary },
    fillBtnText: { fontSize: 13, fontWeight: "800", color: "#fff" },
    typeTag:     { flexDirection: "row", alignItems: "center", gap: 4, backgroundColor: COLORS.primaryPale, borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
    typeTagText: { fontSize: 11, fontWeight: "700", color: COLORS.primary },
    fillOverlay: { flex: 1, backgroundColor: "rgba(0,0,0,0.45)", justifyContent: "flex-end" },
    fillSheet:   { backgroundColor: "#fff", borderTopLeftRadius: 20, borderTopRightRadius: 20, padding: 20, paddingBottom: 36 },
    fillHeader:  { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 10 },
    fillTitle:   { fontSize: 16, fontWeight: "800", color: COLORS.text },
    fillSubtitle: { fontSize: 13, color: COLORS.textMuted, marginTop: 2 },
    fillPatient:  { fontSize: 12, color: COLORS.primary, fontWeight: "600", marginTop: 4 },
    input:        { backgroundColor: "#fff", marginBottom: 10 },
});
