import { StyleSheet } from "react-native";
import { COLORS } from "../../../styles/Styles";

export default StyleSheet.create({
    container:   { flex: 1, backgroundColor: COLORS.bg },
    searchBox:   { backgroundColor: "#fff", padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    searchInput: { backgroundColor: COLORS.bg, elevation: 0 },
    hint:        { fontSize: 12, color: COLORS.textLight, marginTop: 4, marginLeft: 4 },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 14,
        flexDirection: "row", alignItems: "center", gap: 12,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    avatar:      { width: 48, height: 48, borderRadius: 24, backgroundColor: COLORS.primaryPale, alignItems: "center", justifyContent: "center" },
    avatarText:  { fontSize: 20, fontWeight: "800", color: COLORS.primary },
    patientName: { fontSize: 15, fontWeight: "700", color: COLORS.text, marginBottom: 2 },
    infoRow:     { flexDirection: "row", alignItems: "center", gap: 4, marginTop: 2 },
    infoText:    { fontSize: 12, color: COLORS.textMuted },
    emptyText:   { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    modalOverlay: {
        position: "absolute", top: 0, left: 0, right: 0, bottom: 0,
        backgroundColor: "rgba(0,0,0,0.5)", justifyContent: "flex-end",
    },
    modalBox:         { backgroundColor: "#fff", borderTopLeftRadius: 24, borderTopRightRadius: 24, padding: 20, maxHeight: "85%" },
    modalHeader:      { flexDirection: "row", alignItems: "center", marginBottom: 16, gap: 12 },
    modalAvatar:      { width: 52, height: 52, borderRadius: 26, backgroundColor: COLORS.primaryPale, alignItems: "center", justifyContent: "center" },
    modalAvatarText:  { fontSize: 22, fontWeight: "800", color: COLORS.primary },
    modalName:        { fontSize: 17, fontWeight: "800", color: COLORS.text },
    modalEmail:       { fontSize: 13, color: COLORS.textMuted, marginTop: 2 },
    patientInfo:      { backgroundColor: COLORS.bg, borderRadius: 10, padding: 12, marginBottom: 14 },
    patientInfoRow:   { flexDirection: "row", alignItems: "center", gap: 6, marginBottom: 6 },
    patientInfoLabel: { fontSize: 12, color: COLORS.textMuted, minWidth: 80 },
    patientInfoValue: { fontSize: 13, color: COLORS.text, fontWeight: "500", flex: 1 },
    historyTitle:     { fontSize: 14, fontWeight: "700", color: COLORS.text, marginBottom: 10 },
    apptRow:          { flexDirection: "row", alignItems: "center", gap: 10, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    apptDot:          { width: 10, height: 10, borderRadius: 5 },
    apptDate:         { fontSize: 13, fontWeight: "600", color: COLORS.text },
    apptStatus:       { fontSize: 11, fontWeight: "600", marginTop: 2 },
    emptyAppt:        { color: COLORS.textMuted, textAlign: "center", paddingVertical: 12 },
});
