import { StyleSheet } from "react-native";
import { COLORS } from "../../../styles/Styles";

export default StyleSheet.create({
    container: { flex: 1, backgroundColor: COLORS.bg },
    tabBar: {
        backgroundColor: "#fff",
        borderBottomWidth: 1, borderBottomColor: COLORS.border,
        flexDirection: "row", alignItems: "center",
    },
    tab: {
        flexDirection: "row", alignItems: "center", gap: 5,
        paddingHorizontal: 12, paddingVertical: 7,
        borderRadius: 20, borderWidth: 1.5, borderColor: COLORS.border,
        backgroundColor: "#fff",
    },
    tabActive:     { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
    tabText:       { fontSize: 12, fontWeight: "600", color: COLORS.textMuted },
    importBtn:     { flexDirection: "row", alignItems: "center", gap: 4, paddingHorizontal: 12, paddingVertical: 8, marginRight: 10, borderRadius: 10, borderWidth: 1.5, borderColor: COLORS.primary },
    importBtnText: { fontSize: 12, fontWeight: "700", color: COLORS.primary },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 12,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    cardTop:        { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    medicineName:   { fontSize: 14, fontWeight: "700", color: COLORS.text },
    medicineCode:   { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    qtyBadge:       { alignItems: "center", padding: 8, borderRadius: 10, minWidth: 60 },
    qtyText:        { fontSize: 20, fontWeight: "800" },
    qtyLabel:       { fontSize: 10, color: COLORS.textMuted },
    infoRow:        { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 3 },
    infoText:       { fontSize: 12, color: COLORS.textMuted, flex: 1 },
    warningBadge:   { flexDirection: "row", alignItems: "center", gap: 5, borderRadius: 8, padding: 8, marginTop: 6 },
    warningText:    { fontSize: 12, fontWeight: "600", flex: 1 },
    alertTypeBadge: { paddingHorizontal: 8, paddingVertical: 3, borderRadius: 6, alignSelf: "flex-start", marginTop: 3 },
    alertTypeText:  { fontSize: 11, fontWeight: "700" },
    resolveBtn:     { padding: 6, borderRadius: 8, backgroundColor: COLORS.greenPale },
    alertMsg:       { fontSize: 13, color: COLORS.text, marginTop: 4, marginBottom: 4 },
    dateText:       { fontSize: 12, color: COLORS.textLight },
    emptyText:      { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    modalHeader:    { backgroundColor: COLORS.primaryDark, paddingTop: 52, paddingHorizontal: 16, paddingBottom: 16, flexDirection: "row", alignItems: "center", justifyContent: "space-between" },
    modalTitle:     { fontSize: 17, fontWeight: "700", color: "#fff" },
    fieldLabel:     { fontSize: 13, fontWeight: "600", color: COLORS.text, marginBottom: 6 },
    picker:         { flexDirection: "row", justifyContent: "space-between", alignItems: "center", borderWidth: 1.5, borderColor: COLORS.border, borderRadius: 8, padding: 13, backgroundColor: "#fff", marginBottom: 12 },
    dropdown:       { borderWidth: 1, borderColor: COLORS.border, borderRadius: 8, backgroundColor: "#fff", marginBottom: 10, overflow: "hidden" },
    dropdownItem:   { padding: 12, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    dropdownText:   { fontSize: 14, fontWeight: "600", color: COLORS.text },
    dropdownSub:    { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    input:          { backgroundColor: "#fff", marginBottom: 10 },
    row:            { flexDirection: "row", gap: 10 },
});
