import { StyleSheet } from "react-native";
import { COLORS } from "../../styles/Styles";

export const appointmentDetailStyles = StyleSheet.create({
    statusBanner: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        paddingVertical: 14,
    },
    statusText: { color: "#fff", fontWeight: "800", fontSize: 16 },

    doctorCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        marginBottom: 12,
    },
    doctorName: { fontSize: 15, fontWeight: "700", color: COLORS.text },
    doctorSpec: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },

    cardTitle: {
        fontSize: 13,
        fontWeight: "700",
        color: COLORS.textMuted,
        textTransform: "uppercase",
        letterSpacing: 0.5,
        marginBottom: 4,
        paddingHorizontal: 16,
        paddingTop: 14,
    },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 11,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    infoIcon: {
        width: 30, height: 30,
        borderRadius: 8,
        alignItems: "center", justifyContent: "center",
    },
    infoLabel: { fontSize: 11, color: COLORS.textMuted, marginBottom: 1 },
    infoValue: { fontSize: 13, fontWeight: "600", color: COLORS.text },

    costRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 8,
    },
    costLabel: { fontSize: 13, color: COLORS.textMuted },
    costValue: { fontSize: 13, fontWeight: "600", color: COLORS.primary },
    costDivider: { height: 1, backgroundColor: COLORS.border, marginHorizontal: 16, marginVertical: 4 },
    totalValue: { fontSize: 17, fontWeight: "800", color: COLORS.primary },

    refundBanner: {
        flexDirection: "row",
        alignItems: "center",
        gap: 6,
        backgroundColor: COLORS.purplePale,
        borderRadius: 8,
        padding: 10,
        marginHorizontal: 16,
        marginBottom: 8,
    },
    refundText: { fontSize: 13, color: COLORS.purple, fontWeight: "600" },

    payRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 9,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    payLabel: { fontSize: 12, color: COLORS.textMuted },
    payAmount: { fontSize: 16, fontWeight: "800", color: COLORS.primary },
    payMethodRow: { flexDirection: "row", alignItems: "center" },
    payMethodText: { fontSize: 13, fontWeight: "600", color: COLORS.text },
    payMeta: { fontSize: 12, color: COLORS.textMuted },

    payBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        paddingVertical: 13,
        marginTop: 14,
        marginHorizontal: 16,
        marginBottom: 4,
        gap: 8,
        elevation: 3,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    payBtnText: { color: "#fff", fontWeight: "800", fontSize: 14 },
    paidTag: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.greenPale,
        borderRadius: 8,
        paddingVertical: 8,
        marginTop: 10,
        marginHorizontal: 16,
        marginBottom: 4,
    },
    paidTagText: { color: COLORS.green, fontWeight: "700", fontSize: 13 },

    consultBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.green,
        borderRadius: 12,
        paddingVertical: 13,
        marginBottom: 12,
        gap: 8,
        elevation: 3,
        shadowColor: COLORS.green,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    consultBtnText: { color: "#fff", fontWeight: "800", fontSize: 15 },

    cancelBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        borderWidth: 1.5,
        borderColor: COLORS.red,
        borderRadius: 12,
        paddingVertical: 12,
        marginTop: 4,
    },
    cancelBtnText: { color: COLORS.red, fontWeight: "700", fontSize: 14 },
});

export const bookAppointmentStyles = StyleSheet.create({
    form: {
        backgroundColor: "#fff",
        margin: 16,
        borderRadius: 16,
        elevation: 3,
        padding: 20,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    doctorCard: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: COLORS.primaryPale,
        borderRadius: 12,
        padding: 14,
        marginBottom: 14,
    },
    doctorName: {
        fontSize: 15,
        fontWeight: "700",
        color: COLORS.primaryDark,
        marginBottom: 4,
    },
    infoLine: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 2,
    },
    infoText: {
        fontSize: 12,
        color: COLORS.primary,
        fontWeight: "600",
    },
    countdown: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: COLORS.primaryPale,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 8,
        marginBottom: 12,
        borderWidth: 1,
        borderColor: COLORS.primaryMid,
    },
    countdownExpired: {
        backgroundColor: COLORS.redPale,
        borderColor: COLORS.redLight,
    },
    countdownText: {
        fontSize: 13,
        fontWeight: "600",
        color: COLORS.primary,
    },
    confirmBtn: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center",
        gap: 8,
        backgroundColor: COLORS.primary,
        borderRadius: 12,
        paddingVertical: 14,
        marginBottom: 10,
        elevation: 3,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 3 },
        shadowOpacity: 0.3,
        shadowRadius: 6,
    },
    confirmBtnText: {
        color: "#fff",
        fontWeight: "800",
        fontSize: 15,
    },
});

export const slotSelectStyles = StyleSheet.create({
    dateHeader: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        paddingHorizontal: 16,
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: COLORS.border,
    },
    specialtyLabel: {
        fontSize: 11,
        color: COLORS.primary,
        fontWeight: "700",
        textTransform: "uppercase",
        letterSpacing: 0.5,
        marginBottom: 1,
    },
    dateText: {
        fontSize: 14,
        fontWeight: "700",
        color: COLORS.text,
    },
    card: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        borderRadius: 14,
        padding: 14,
        marginBottom: 10,
        elevation: 2,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
    },
    docName: {
        fontSize: 14,
        fontWeight: "700",
        color: COLORS.text,
    },
    timeRow: {
        flexDirection: "row",
        alignItems: "center",
        marginTop: 4,
    },
    timeText: {
        fontSize: 13,
        color: COLORS.primary,
        fontWeight: "600",
    },
    slotInfo: {
        fontSize: 11,
        color: COLORS.textMuted,
        marginTop: 3,
    },
    selectBtn: {
        backgroundColor: COLORS.primary,
        borderRadius: 10,
        paddingHorizontal: 14,
        paddingVertical: 8,
    },
    selectBtnText: {
        color: "#fff",
        fontSize: 12,
        fontWeight: "700",
    },
    emptyText: {
        marginTop: 12,
        fontSize: 14,
        color: COLORS.textMuted,
        fontWeight: "600",
        textAlign: "center",
    },
    emptySubText: {
        marginTop: 4,
        fontSize: 12,
        color: COLORS.textLight,
        textAlign: "center",
    },
});

export const specialtySelectStyles = StyleSheet.create({
    searchWrap: {
        flexDirection: "row",
        alignItems: "center",
        gap: 10,
        margin: 12,
        paddingHorizontal: 14,
        paddingVertical: 10,
        backgroundColor: "#f5f6fa",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: COLORS.border,
    },
    searchInput: {
        flex: 1,
        fontSize: 14,
        color: COLORS.text,
    },
    card: {
        flexDirection: "row",
        alignItems: "center",
        paddingHorizontal: 16,
        paddingVertical: 14,
        backgroundColor: "#fff",
    },
    cardTop: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-start",
        marginBottom: 3,
    },
    specName: {
        flex: 1,
        fontSize: 14,
        fontWeight: "800",
        color: COLORS.text,
        marginRight: 8,
    },
    specFee: {
        fontSize: 14,
        fontWeight: "700",
        color: COLORS.primary,
        flexShrink: 0,
    },
    specNote: {
        fontSize: 12,
        color: COLORS.textMuted,
        fontStyle: "italic",
        marginBottom: 2,
    },
    specDesc: {
        fontSize: 12,
        color: COLORS.textMuted,
        lineHeight: 17,
    },
});

export const dateSelectStyles = StyleSheet.create({
    calCard: {
        margin: 16,
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 12,
        elevation: 3,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    monthNav: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        marginBottom: 16,
        paddingHorizontal: 4,
    },
    navBtn: {
        width: 36, height: 36,
        borderRadius: 8,
        backgroundColor: "#f0f0f0",
        alignItems: "center", justifyContent: "center",
    },
    navBtnActive: {
        backgroundColor: COLORS.primary,
    },
    monthTitle: {
        fontSize: 16,
        fontWeight: "800",
        color: COLORS.primary,
    },
    weekRow: {
        flexDirection: "row",
        marginBottom: 4,
    },
    weekDay: {
        textAlign: "center",
        fontSize: 12,
        fontWeight: "700",
        color: COLORS.textMuted,
        paddingVertical: 4,
    },
    weekDaySun: {
        color: COLORS.red,
    },
    daysGrid: {
        flexDirection: "row",
        flexWrap: "wrap",
    },
    dayCell: {
        alignItems: "center",
        justifyContent: "center",
        borderRadius: 8,
        marginVertical: 2,
        paddingVertical: 4,
    },
    dayCellToday: {
        borderWidth: 2,
        borderColor: COLORS.primary,
    },
    dayCellAvail: {
        backgroundColor: COLORS.primary,
    },
    dayCellSelected: {
        backgroundColor: COLORS.primaryDark,
    },
    dayCellHoliday: {
        borderWidth: 2,
        borderColor: COLORS.orange,
    },
    dayText: {
        fontSize: 14,
        fontWeight: "600",
        color: COLORS.text,
    },
    dayTextPast: {
        color: COLORS.textLight,
        fontWeight: "400",
    },
    dayTextAvail: {
        color: "#fff",
        fontWeight: "700",
    },
    dayTextSelected: {
        color: "#fff",
        fontWeight: "800",
    },
    dayTextToday: {
        color: COLORS.primary,
        fontWeight: "800",
    },
    subLabel: {
        fontSize: 8,
        fontWeight: "600",
    },
    subLabelWhite: { color: "#fff" },
    subLabelBlue:  { color: COLORS.primary },
    subLabelOrange: { fontSize: 8, fontWeight: "600", color: COLORS.orange },
    legendCard: {
        marginHorizontal: 16,
        marginBottom: 24,
    },
    hintBorder: {
        borderLeftWidth: 3,
        borderLeftColor: COLORS.primary,
        paddingLeft: 10,
        paddingVertical: 6,
        marginBottom: 14,
    },
    hintText: {
        fontSize: 13,
        color: COLORS.text,
    },
    legendRow: {
        gap: 6,
    },
    legendItem: {
        flexDirection: "row",
        alignItems: "center",
        gap: 8,
        marginBottom: 4,
    },
    legendBox: {
        width: 20, height: 20,
        borderRadius: 4,
    },
    legendText: {
        fontSize: 12,
        color: COLORS.textMuted,
    },
});
