import { StyleSheet, Platform } from "react-native";
import { COLORS } from "../../../styles/Styles";

export default StyleSheet.create({
    summaryBanner: {
        flexDirection: "row", backgroundColor: COLORS.orange,
        paddingVertical: 14, paddingHorizontal: 24,
        justifyContent: "space-around", alignItems: "center",
    },
    summaryItem:    { alignItems: "center" },
    summaryValue:   { fontSize: 20, fontWeight: "800", color: "#fff" },
    summaryLabel:   { fontSize: 12, color: "rgba(255,255,255,0.85)", marginTop: 2 },
    summaryDivider: { width: 1, height: 36, backgroundColor: "rgba(255,255,255,0.4)" },
    filterBar:   { backgroundColor: "#fff", borderBottomWidth: 1, borderBottomColor: COLORS.border },
    chip:        { paddingHorizontal: 14, paddingVertical: 6, borderRadius: 20, borderWidth: 1.5, borderColor: COLORS.border, backgroundColor: "#fff" },
    chipText:    { fontSize: 12, fontWeight: "600", color: COLORS.textMuted },
    card: {
        backgroundColor: "#fff", borderRadius: 14, padding: 14,
        elevation: 2, shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 }, shadowOpacity: 0.07, shadowRadius: 4,
    },
    cardTop:     { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    patientName: { fontSize: 15, fontWeight: "700", color: COLORS.text },
    methodText:  { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    statusBadge: { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    statusText:  { fontSize: 11, fontWeight: "700" },
    amountRow:   { flexDirection: "row", alignItems: "center", marginBottom: 4 },
    amountLabel: { fontSize: 13, color: COLORS.textMuted, marginRight: 6 },
    amountValue: { fontSize: 16, fontWeight: "800", color: COLORS.primary },
    dateText:    { fontSize: 12, color: COLORS.textLight, marginBottom: 10 },
    collectBtn: {
        flexDirection: "row", alignItems: "center", justifyContent: "center",
        gap: 8, backgroundColor: COLORS.orange, borderRadius: 10, paddingVertical: 10,
    },
    collectBtnText:   { color: "#fff", fontSize: 14, fontWeight: "700" },
    emptyText:        { color: COLORS.textMuted, marginTop: 12, fontSize: 14 },
    collectContainer: { flex: 1, backgroundColor: COLORS.bg },
    amountDisplay: {
        backgroundColor: COLORS.green, paddingTop: Platform.OS === "ios" ? 56 : 48,
        paddingBottom: 32, alignItems: "center",
    },
    collectLabel:      { fontSize: 14, color: "rgba(255,255,255,0.8)" },
    collectAmount:     { fontSize: 38, fontWeight: "900", color: "#fff", marginVertical: 6 },
    collectPatient:    { fontSize: 16, color: "rgba(255,255,255,0.9)", fontWeight: "600" },
    collectCard:       { margin: 16, backgroundColor: "#fff", borderRadius: 16, padding: 20, elevation: 3 },
    collectCardTitle:  { fontSize: 16, fontWeight: "700", color: COLORS.text, marginBottom: 16 },
    infoRow:   { flexDirection: "row", alignItems: "center", marginBottom: 10, gap: 8 },
    infoLabel: { fontSize: 13, color: COLORS.textMuted, flex: 1 },
    infoValue: { fontSize: 13, fontWeight: "600", color: COLORS.text },
    noteLabel: { fontSize: 13, color: COLORS.textMuted, marginTop: 12, marginBottom: 6 },
    noteInput: {
        borderWidth: 1.5, borderColor: COLORS.border,
        borderRadius: 8, padding: 10,
        fontSize: 14, color: COLORS.text, marginBottom: 16,
    },
    steps:      { backgroundColor: COLORS.greenPale, borderRadius: 10, padding: 12, marginBottom: 20 },
    stepRow:    { flexDirection: "row", alignItems: "flex-start", gap: 8, marginBottom: 8 },
    stepText:   { fontSize: 13, color: COLORS.text, flex: 1 },
    confirmBtn: { borderRadius: 10, marginBottom: 4 },
});
