# Generated by Django 6.0.3 on 2026-05-03 15:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['full_name'], 'verbose_name': 'Bác sĩ'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Bệnh nhân'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': 'Chuyên khoa'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='import_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
