# Generated by Django 6.0.3 on 2026-05-26 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointmentservice',
            options={'ordering': ['id'], 'verbose_name': 'Dịch vụ trong lịch hẹn', 'verbose_name_plural': 'Dịch vụ trong lịch hẹn'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'ordering': ['-id'], 'verbose_name': 'Tư vấn trực tuyến', 'verbose_name_plural': 'Tư vấn trực tuyến'},
        ),
        migrations.AlterModelOptions(
            name='prescriptiondetail',
            options={'ordering': ['id'], 'verbose_name': 'Chi tiết đơn thuốc', 'verbose_name_plural': 'Chi tiết đơn thuốc'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'ordering': ['-test_date'], 'verbose_name': 'Kết quả cận lâm sàng', 'verbose_name_plural': 'Kết quả cận lâm sàng'},
        ),
        migrations.AddField(
            model_name='consultation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
