# Generated by Django 6.0.3 on 2026-05-12 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_alter_doctor_options_alter_medicine_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Bệnh nhân'), ('doctor', 'Bác sĩ'), ('admin', 'Quản trị viên')], default='patient', max_length=20),
        ),
    ]
