# Generated by Django 6.0.3 on 2026-05-26 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0002_alter_appointmentservice_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together=set(),
        ),
    ]
