# Generated by Django 6.0.3 on 2026-05-26 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0003_alter_appointment_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='push_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('appointment_reminder', 'Nhắc lịch hẹn'), ('appointment_confirmed', 'Xác nhận lịch hẹn'), ('appointment_cancelled', 'Hủy lịch hẹn'), ('prescription_ready', 'Đơn thuốc sẵn sàng'), ('payment_success', 'Thanh toán thành công'), ('inventory_alert', 'Cảnh báo kho thuốc'), ('system', 'Hệ thống'), ('test_result_ready', 'Kết quả xét nghiệm')], default='system', max_length=50),
        ),
    ]
