# Generated by Django 6.0.3 on 2026-05-18 10:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0004_remove_user_created_at_alter_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Kết quả cận lâm sàng'},
        ),
        migrations.AddField(
            model_name='testresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Nhân viên nhập kết quả', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_test_results', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='test_type',
            field=models.CharField(choices=[('blood', 'Xét nghiệm máu'), ('urine', 'Xét nghiệm nước tiểu'), ('stool', 'Xét nghiệm phân'), ('micro', 'Vi sinh / Cấy khuẩn'), ('xray', 'Chụp X-quang'), ('ct', 'Chụp CT'), ('mri', 'Chụp MRI'), ('ultrasound', 'Siêu âm'), ('endoscopy', 'Nội soi'), ('ecg', 'Điện tâm đồ (ECG)'), ('other', 'Khác')], default='other', help_text='Loại cận lâm sàng', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('in_progress', 'Đang khám'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy'), ('no_show', 'Không đến')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='file_attachment',
            field=models.FileField(blank=True, help_text='File kết quả (hình chụp, PDF...)', null=True, upload_to='test_results/'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='reference_range',
            field=models.CharField(blank=True, help_text='Khoảng tham chiếu bình thường', max_length=100),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='result',
            field=models.TextField(help_text='Kết quả'),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='test_name',
            field=models.CharField(help_text='Tên xét nghiệm/chụp chiếu cụ thể', max_length=255),
        ),
        migrations.AlterField(
            model_name='testresult',
            name='unit',
            field=models.CharField(blank=True, help_text='Đơn vị (nếu có)', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Bệnh nhân'), ('doctor', 'Bác sĩ'), ('staff', 'Nhân viên y tế'), ('admin', 'Quản trị viên')], default='patient', max_length=20),
        ),
    ]
