# Generated by Django 6.0.3 on 2026-05-28 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_testresult_status_alter_testresult_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='warning_threshold',
            field=models.PositiveIntegerField(default=10, help_text='Ngưỡng cảnh báo tồn kho thấp (tính trên tổng tất cả lô còn hạn)'),
        ),
    ]
