# Generated by Django 6.0.3 on 2026-05-24 17:24

import django.contrib.auth.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0005_alter_testresult_options_testresult_entered_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id'], 'verbose_name': 'Bác sĩ', 'verbose_name_plural': 'Bác sĩ'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'verbose_name': 'Lịch làm việc', 'verbose_name_plural': 'Lịch làm việc'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Người dùng', 'verbose_name_plural': 'Người dùng'},
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='full_name',
        ),
    ]
