# Generated by Django 6.0.3 on 2026-05-24 18:46

import ckeditor.fields
import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0006_alter_doctor_options_alter_doctorschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-appointment_date'], 'verbose_name': 'Lịch hẹn', 'verbose_name_plural': 'Lịch hẹn'},
        ),
        migrations.AlterModelOptions(
            name='appointmentservice',
            options={'verbose_name': 'Dịch vụ trong lịch hẹn', 'verbose_name_plural': 'Dịch vụ trong lịch hẹn'},
        ),
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['sent_at'], 'verbose_name': 'Tin nhắn tư vấn', 'verbose_name_plural': 'Tin nhắn tư vấn'},
        ),
        migrations.AlterModelOptions(
            name='consultation',
            options={'verbose_name': 'Tư vấn trực tuyến', 'verbose_name_plural': 'Tư vấn trực tuyến'},
        ),
        migrations.AlterModelOptions(
            name='doctorschedule',
            options={'ordering': ['date', 'start_time'], 'verbose_name': 'Lịch làm việc', 'verbose_name_plural': 'Lịch làm việc'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': 'Tồn kho thuốc', 'verbose_name_plural': 'Tồn kho thuốc'},
        ),
        migrations.AlterModelOptions(
            name='inventoryalert',
            options={'ordering': ['-created_at'], 'verbose_name': 'Cảnh báo kho thuốc', 'verbose_name_plural': 'Cảnh báo kho thuốc'},
        ),
        migrations.AlterModelOptions(
            name='medicalrecord',
            options={'ordering': ['-created_at'], 'verbose_name': 'Hồ sơ bệnh án', 'verbose_name_plural': 'Hồ sơ bệnh án'},
        ),
        migrations.AlterModelOptions(
            name='medicine',
            options={'ordering': ['name'], 'verbose_name': 'Thuốc', 'verbose_name_plural': 'Thuốc'},
        ),
        migrations.AlterModelOptions(
            name='medicinecategory',
            options={'ordering': ['name'], 'verbose_name': 'Danh mục thuốc', 'verbose_name_plural': 'Danh mục thuốc'},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thông báo', 'verbose_name_plural': 'Thông báo'},
        ),
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['id'], 'verbose_name': 'Bệnh nhân', 'verbose_name_plural': 'Bệnh nhân'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Thanh toán', 'verbose_name_plural': 'Thanh toán'},
        ),
        migrations.AlterModelOptions(
            name='prescription',
            options={'ordering': ['-created_at'], 'verbose_name': 'Đơn thuốc', 'verbose_name_plural': 'Đơn thuốc'},
        ),
        migrations.AlterModelOptions(
            name='prescriptiondetail',
            options={'verbose_name': 'Chi tiết đơn thuốc', 'verbose_name_plural': 'Chi tiết đơn thuốc'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['specialty', 'name'], 'verbose_name': 'Dịch vụ y tế', 'verbose_name_plural': 'Dịch vụ y tế'},
        ),
        migrations.AlterModelOptions(
            name='specialty',
            options={'ordering': ['name'], 'verbose_name': 'Chuyên khoa', 'verbose_name_plural': 'Chuyên khoa'},
        ),
        migrations.AlterModelOptions(
            name='testresult',
            options={'verbose_name': 'Kết quả cận lâm sàng', 'verbose_name_plural': 'Kết quả cận lâm sàng'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='patient',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='patient',
        ),
        migrations.AlterField(
            model_name='doctor',
            name='bio',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='dosage',
            field=models.CharField(help_text='Liều dùng mỗi lần', max_length=100),
        ),
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='frequency',
            field=models.CharField(help_text='Số lần/ngày', max_length=100),
        ),
        migrations.AlterField(
            model_name='specialty',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('position', models.CharField(choices=[('nurse', 'Điều dưỡng viên'), ('lab_tech', 'Kỹ thuật viên xét nghiệm'), ('pharmacist', 'Dược sĩ'), ('receptionist', 'Nhân viên lễ tân'), ('xray_tech', 'Kỹ thuật viên X-quang')], default='nurse', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='clinic_app.specialty')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nhân viên y tế',
                'verbose_name_plural': 'Nhân viên y tế',
                'db_table': 'staff',
                'ordering': ['id'],
            },
        ),
        migrations.AlterField(
            model_name='testresult',
            name='entered_by',
            field=models.ForeignKey(blank=True, help_text='Nhân viên nhập kết quả', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_test_results', to='clinic_app.staff'),
        ),
    ]
