# Generated by Django 6.0.3 on 2026-05-25 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0007_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payment',
            name='prescription',
            field=models.OneToOneField(blank=True, help_text='Thanh toán tiền thuốc', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clinic_app.prescription'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='dispensed_by',
            field=models.ForeignKey(blank=True, help_text='Dược sĩ cấp phát', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispensed_prescriptions', to='clinic_app.staff'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='appointment',
            field=models.OneToOneField(blank=True, help_text='Thanh toán tiền khám + dịch vụ', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='clinic_app.appointment'),
        ),
    ]
