# Generated by Django 6.0.3 on 2026-05-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic_app', '0007_inventory_add_dispose_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='warning_threshold',
            field=models.PositiveIntegerField(default=50, help_text='Ngưỡng cảnh báo tồn kho thấp (tính trên tổng tất cả lô còn hạn)'),
        ),
    ]
