import { StyleSheet } from "react-native";
import { COLORS } from "../../styles/Styles";

export const profileStyles = StyleSheet.create({
    header: {
        backgroundColor: COLORS.primaryDark,
        paddingTop: 16,
        paddingHorizontal: 20,
        paddingBottom: 36,
        alignItems: "center",
        gap: 6,
    },
    name:      { color: "#fff", fontSize: 20, fontWeight: "800", marginTop: 6 },
    roleBadge: { backgroundColor: "rgba(255,255,255,0.2)", borderRadius: 12, paddingHorizontal: 14, paddingVertical: 4 },
    roleText:  { color: "#fff", fontSize: 11, fontWeight: "600" },
    email:     { color: "rgba(255,255,255,0.7)", fontSize: 12 },
    statsRow: {
        flexDirection: "row",
        backgroundColor: "#fff",
        borderRadius: 16,
        marginHorizontal: 16,
        marginTop: -22,
        elevation: 6,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 12,
        overflow: "hidden",
        zIndex: 10,
    },
    statItem:   { flex: 1, paddingVertical: 16, alignItems: "center" },
    statBorder: { borderLeftWidth: 1, borderRightWidth: 1, borderColor: COLORS.border },
    statNum:    { fontSize: 22, fontWeight: "800", color: COLORS.primary },
    statLabel:  { fontSize: 10, color: COLORS.textMuted, marginTop: 2 },
    section:    { marginHorizontal: 16, marginTop: 20 },
    sectionTitle: {
        fontSize: 11, fontWeight: "700", color: COLORS.textLight,
        letterSpacing: 0.8, marginBottom: 8, paddingLeft: 4,
    },
    card: {
        backgroundColor: "#fff",
        borderRadius: 16,
        overflow: "hidden",
        elevation: 2,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.07,
        shadowRadius: 6,
    },
    infoRow: {
        flexDirection: "row", alignItems: "center",
        paddingHorizontal: 16, paddingVertical: 12,
        borderBottomWidth: 1, borderBottomColor: COLORS.border,
    },
    infoLabel:  { fontSize: 11, color: COLORS.textMuted, width: 90 },
    infoValue:  { fontSize: 13, color: COLORS.text, fontWeight: "500", flex: 1 },
    menuRow: {
        flexDirection: "row", alignItems: "center",
        paddingHorizontal: 16, paddingVertical: 14,
        borderBottomWidth: 1, borderBottomColor: COLORS.border,
        gap: 12,
    },
    menuIcon:  { width: 38, height: 38, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    menuLabel: { fontSize: 13, fontWeight: "600", color: COLORS.text },
    menuSub:   { fontSize: 11, color: COLORS.textMuted, marginTop: 1 },
    badgeWrap: {
        backgroundColor: COLORS.redLight, borderRadius: 8,
        paddingHorizontal: 6, paddingVertical: 2, marginRight: 6,
    },
    badgeText:  { color: "#fff", fontSize: 10, fontWeight: "700" },
    logoutBtn: {
        margin: 16,
        backgroundColor: "#fff0f0",
        borderWidth: 1.5, borderColor: "#ffcdd2",
        borderRadius: 16, paddingVertical: 14,
        flexDirection: "row", alignItems: "center", justifyContent: "center", gap: 8,
    },
    logoutText: { color: COLORS.redLight, fontSize: 14, fontWeight: "700" },
});

export const paymentsListStyles = StyleSheet.create({
    card: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        borderRadius: 14,
        padding: 14,
        marginBottom: 10,
        elevation: 2,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 6,
    },
    methodIcon: { width: 46, height: 46, borderRadius: 13, alignItems: "center", justifyContent: "center" },
    topRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 4,
    },
    amount:     { fontSize: 16, fontWeight: "800", color: COLORS.text },
    badge:      { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 3 },
    badgeText:  { fontSize: 11, fontWeight: "700" },
    bottomRow:  { flexDirection: "row", alignItems: "center" },
    meta:       { fontSize: 11, color: COLORS.textMuted },
    metaDot:    { fontSize: 11, color: COLORS.textLight },
    note:       { fontSize: 11, color: COLORS.textLight, marginTop: 2 },
});

export const medicalRecordsStyles = StyleSheet.create({
    row: { flexDirection: "row", alignItems: "center" },
    testResult: {},
});

export const prescriptionDetailStyles = StyleSheet.create({
    header: {
        backgroundColor: COLORS.primaryDark,
        paddingTop: 16,
        paddingHorizontal: 20,
        paddingBottom: 24,
        alignItems: "center",
        gap: 6,
    },
    iconWrap: {
        width: 64, height: 64, borderRadius: 20,
        backgroundColor: "rgba(255,255,255,0.18)",
        alignItems: "center", justifyContent: "center",
        marginBottom: 8,
    },
    title:       { color: "#fff", fontSize: 18, fontWeight: "800" },
    subtitle:    { color: "rgba(255,255,255,0.75)", fontSize: 13, marginTop: 4 },
    statusBadge: {
        marginTop: 8, paddingHorizontal: 14, paddingVertical: 5,
        borderRadius: 16, backgroundColor: "rgba(255,255,255,0.2)",
    },
    statusText:  { color: "#fff", fontSize: 12, fontWeight: "700" },
    card: {
        margin: 16, marginBottom: 0, backgroundColor: "#fff",
        borderRadius: 14, padding: 16, elevation: 2,
        shadowColor: "#000", shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.07, shadowRadius: 4,
    },
    cardTitle:  { fontSize: 13, fontWeight: "700", color: COLORS.textMuted, textTransform: "uppercase", letterSpacing: 0.5, marginBottom: 12 },
    infoRow:    { flexDirection: "row", alignItems: "center", marginBottom: 8 },
    infoLabel:  { fontSize: 13, color: COLORS.textMuted, marginLeft: 6, flex: 1 },
    infoValue:  { fontSize: 13, color: COLORS.text, fontWeight: "500" },
    medItem: {
        backgroundColor: COLORS.bg, borderRadius: 10, padding: 10, marginBottom: 8,
    },
    medName:   { fontSize: 14, fontWeight: "700", color: COLORS.text, marginBottom: 4 },
    medDetail: { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },
    emptyText: { color: COLORS.textMuted, fontSize: 13, textAlign: "center", paddingVertical: 20 },
});
