import { StyleSheet, Platform } from "react-native";

const SCREEN_W = 375;

export const COLORS = {
    primary:      "#1565c0",
    primaryDark:  "#0d47a1",
    primaryLight: "#1976d2",
    primaryPale:  "#e3f2fd",
    primaryMid:   "#bbdefb",
    green:        "#2e7d32",
    greenLight:   "#4caf50",
    greenPale:    "#e8f5e9",
    orange:       "#e65100",
    orangeLight:  "#ff9800",
    orangePale:   "#fff3e0",
    red:          "#c62828",
    redLight:     "#f44336",
    redPale:      "#fce4ec",
    purple:       "#6a1b9a",
    purpleLight:  "#ab47bc",
    purplePale:   "#f3e5f5",
    teal:         "#00695c",
    tealLight:    "#26a69a",
    tealPale:     "#e0f7fa",
    bg:           "#f0f4fa",
    white:        "#ffffff",
    text:         "#1a2340",
    textMuted:    "#5a6a85",
    textLight:    "#8fa0ba",
    border:       "#dde6f5",
};

export const ICON_BG = {
    blue:   { bg: "#e3f2fd", color: "#1565c0" },
    green:  { bg: "#e8f5e9", color: "#2e7d32" },
    orange: { bg: "#fff3e0", color: "#e65100" },
    purple: { bg: "#f3e5f5", color: "#6a1b9a" },
    teal:   { bg: "#e0f7fa", color: "#00695c" },
    pink:   { bg: "#fce4ec", color: "#c2185b" },
    indigo: { bg: "#e8eaf6", color: "#283593" },
    amber:  { bg: "#fff8e1", color: "#f57f17" },
};

export const STATUS_CONFIG = {
    all:         { label: "Tất cả",       color: COLORS.textMuted },
    pending:     { label: "Chờ xác nhận", color: COLORS.orange },
    confirmed:   { label: "Đã xác nhận",  color: COLORS.green },
    in_progress: { label: "Đang khám",    color: COLORS.purple },
    completed:   { label: "Hoàn thành",   color: COLORS.primary },
    cancelled:   { label: "Đã hủy",       color: COLORS.red },
    no_show:     { label: "Không đến",    color: COLORS.textLight },
};

const Styles = StyleSheet.create({
    container:  { flex: 1, backgroundColor: COLORS.bg },
    padding:    { padding: 16 },
    margin:     { marginBottom: 12 },
    center:     { alignItems: "center", justifyContent: "center" },
    row:        { flexDirection: "row", alignItems: "center" },
    flex1:      { flex: 1 },
    scrollContent: { padding: 16, paddingBottom: 32 },

    card: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        elevation: 2,
        shadowColor: "#1565c0",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    cardPressable: {
        backgroundColor: COLORS.white,
        borderRadius: 16,
        padding: 16,
        marginBottom: 12,
        elevation: 2,
        shadowColor: "#1565c0",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
        borderWidth: 1.5,
        borderColor: "transparent",
    },

    title: {
        fontSize: 20,
        fontWeight: "800",
        color: COLORS.primaryDark,
        marginBottom: 8,
    },
    subtitle:   { fontSize: 15, fontWeight: "700", color: COLORS.text },
    text:       { fontSize: 13, color: COLORS.textMuted, lineHeight: 20 },
    textSmall:  { fontSize: 11, color: COLORS.textLight },
    sectionHeader: {
        fontSize: 15,
        fontWeight: "800",
        color: COLORS.primary,
        marginTop: 4,
        marginBottom: 10,
    },
    divider: {
        height: 1,
        backgroundColor: COLORS.border,
        marginVertical: 10,
    },

    badge: {
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 20,
        alignSelf: "flex-start",
    },
    badgeText: { fontSize: 11, fontWeight: "700", color: "#fff" },

    avatar:      { width: 80,  height: 80,  borderRadius: 40 },
    avatarLarge: { width: 100, height: 100, borderRadius: 50 },
    avatarCircle: {
        width: 54,
        height: 54,
        borderRadius: 16,
        backgroundColor: COLORS.primaryPale,
        alignItems: "center",
        justifyContent: "center",
    },

    btnPrimary: {
        backgroundColor: COLORS.primary,
        borderRadius: 14,
        paddingVertical: 14,
        alignItems: "center",
        marginBottom: 10,
        elevation: 3,
        shadowColor: COLORS.primary,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    btnPrimaryText: { color: "#fff", fontWeight: "800", fontSize: 15 },
    btnOutline: {
        borderWidth: 1.5,
        borderColor: COLORS.primary,
        borderRadius: 14,
        paddingVertical: 13,
        alignItems: "center",
        marginBottom: 10,
    },
    btnOutlineText: { color: COLORS.primary, fontWeight: "700", fontSize: 15 },

    header: {
        paddingHorizontal: 20,
        paddingTop: Platform.OS === "ios" ? 56 : 48,
        paddingBottom: 24,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
    },
    headerTitle:    { fontSize: 20, fontWeight: "800", color: "#fff" },
    headerSubtitle: { fontSize: 13, color: "rgba(255,255,255,0.8)", marginTop: 4 },
    notifBtn: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: "rgba(255,255,255,0.18)",
        alignItems: "center",
        justifyContent: "center",
    },

    section:       { margin: 16, marginBottom: 0 },
    sectionRow:    { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
    sectionTitle:  { fontSize: 16, fontWeight: "700", color: COLORS.text, marginBottom: 12 },
    seeAll:        { fontSize: 13, color: COLORS.primary, fontWeight: "600" },

    statCard: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 14,
        flexDirection: "row",
        alignItems: "center",
        borderLeftWidth: 4,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
        marginBottom: 2,
    },
    statIcon:  { width: 42, height: 42, borderRadius: 10, alignItems: "center", justifyContent: "center" },
    statValue: { fontSize: 22, fontWeight: "800", color: COLORS.text },
    statLabel: { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },

    actionsGrid: { flexDirection: "row", flexWrap: "wrap", gap: 10 },
    actionBtn: {
        width: "31%",
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 12,
        alignItems: "center",
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    actionIcon:  { width: 46, height: 46, borderRadius: 12, alignItems: "center", justifyContent: "center", marginBottom: 8 },
    actionLabel: { fontSize: 11, fontWeight: "600", color: COLORS.text, textAlign: "center" },

    apptItem: {
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 12,
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 8,
        elevation: 1,
        gap: 10,
    },
    timeBox:     { padding: 8, borderRadius: 8, alignItems: "center", minWidth: 56 },
    timeText:    { fontSize: 13, fontWeight: "700", color: COLORS.primary },
    apptPatient: { fontSize: 14, fontWeight: "700", color: COLORS.text },
    apptSub:     { fontSize: 12, color: COLORS.textMuted, marginTop: 2 },

    statusBadge:  { paddingHorizontal: 8, paddingVertical: 4, borderRadius: 8 },
    statusText:   { fontSize: 10, fontWeight: "700" },

    filterChip: {
        paddingHorizontal: 14,
        paddingVertical: 6,
        borderRadius: 20,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        backgroundColor: "#fff",
    },
    filterChipActive: { borderColor: "transparent" },
    filterChipText:       { fontSize: 12, fontWeight: "600", color: COLORS.textMuted },
    filterChipTextActive: { color: "#fff" },

    revenueRow:   { flexDirection: "row", margin: 16, marginBottom: 0, gap: 10 },
    revenueCard:  { flex: 1, borderRadius: 14, padding: 14 },
    revenueLabel: { fontSize: 11, color: "rgba(255,255,255,0.8)", marginTop: 6 },
    revenueValue: { fontSize: 15, fontWeight: "800", color: "#fff", marginTop: 2 },

    profileHeader: {
        paddingTop: Platform.OS === "ios" ? 56 : 48,
        paddingBottom: 28,
        paddingHorizontal: 20,
        alignItems: "center",
    },
    profileAvatarWrap: {
        width: 90, height: 90, borderRadius: 45,
        backgroundColor: "rgba(255,255,255,0.25)",
        alignItems: "center", justifyContent: "center",
        marginBottom: 12,
        borderWidth: 3, borderColor: "rgba(255,255,255,0.5)",
        overflow: "hidden",
    },
    profileAvatar:   { width: 90, height: 90, borderRadius: 45 },
    profileName:     { fontSize: 20, fontWeight: "800", color: "#fff", textAlign: "center" },
    profileRoleTag:  {
        flexDirection: "row", alignItems: "center", gap: 4,
        marginTop: 6, paddingHorizontal: 12, paddingVertical: 4,
        borderRadius: 16, backgroundColor: "rgba(255,255,255,0.2)",
    },
    profileRoleText: { fontSize: 12, fontWeight: "700", color: "#fff" },
    profileInfoRow: {
        flexDirection: "row", justifyContent: "center", gap: 16,
        marginTop: 12,
    },
    profileInfoItem: { alignItems: "center" },
    profileInfoVal:  { fontSize: 16, fontWeight: "800", color: "#fff" },
    profileInfoLbl:  { fontSize: 11, color: "rgba(255,255,255,0.75)", marginTop: 2 },

    menuCard:    { backgroundColor: "#fff", borderRadius: 16, marginHorizontal: 16, marginBottom: 12, overflow: "hidden" },
    menuItem:    { flexDirection: "row", alignItems: "center", padding: 14, borderBottomWidth: 1, borderBottomColor: COLORS.border },
    menuItemLast:{ borderBottomWidth: 0 },
    menuIcon:    { width: 36, height: 36, borderRadius: 10, alignItems: "center", justifyContent: "center", marginRight: 12 },
    menuLabel:   { flex: 1, fontSize: 14, fontWeight: "600", color: COLORS.text },

    searchWrap:  { backgroundColor: "#fff", paddingHorizontal: 12, paddingTop: 10, paddingBottom: 4 },
    searchInput: { backgroundColor: COLORS.bg, elevation: 0, height: 44 },

    appointmentCard: {
        backgroundColor: "#fff",
        borderRadius: 14,
        padding: 14,
        elevation: 2,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.07,
        shadowRadius: 4,
    },
    apptCardTop:  { flexDirection: "row", alignItems: "center", marginBottom: 8, gap: 8 },
    apptDot:      { width: 10, height: 10, borderRadius: 5 },
    apptName:     { fontSize: 15, fontWeight: "700", color: COLORS.text },
    apptDoctor:   { fontSize: 12, color: COLORS.textMuted, marginTop: 1 },
    apptInfoRow:  { flexDirection: "row", alignItems: "center", gap: 5, marginBottom: 4 },
    apptInfoText: { fontSize: 12, color: COLORS.textMuted },
    apptReason:   { fontSize: 13, color: COLORS.textMuted, marginBottom: 8 },
    apptActions:  { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 6 },
    apptActionBtn: {
        flexDirection: "row", alignItems: "center", gap: 4,
        paddingHorizontal: 10, paddingVertical: 6,
        borderRadius: 8, borderWidth: 1.5, backgroundColor: "#fff",
    },
    apptActionLabel: { fontSize: 11, fontWeight: "700" },

    calendarWrap: {
        backgroundColor: "#fff",
        borderRadius: 16,
        padding: 16,
        marginBottom: 16,
        elevation: 2,
        shadowColor: "#1565c0",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.08,
        shadowRadius: 8,
    },
    calendarHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "center", marginBottom: 12 },
    calendarMonthTxt: { fontSize: 15, fontWeight: "700", color: COLORS.text },
    calendarGrid: { flexDirection: "row", flexWrap: "wrap", gap: 6 },
    calendarDayName: {
        width: (SCREEN_W - 96) / 7,
        textAlign: "center",
        fontSize: 11,
        fontWeight: "700",
        color: COLORS.textMuted,
        marginBottom: 4,
    },
    calendarDay: {
        width: (SCREEN_W - 96) / 7,
        height: (SCREEN_W - 96) / 7,
        borderRadius: 8,
        alignItems: "center",
        justifyContent: "center",
        backgroundColor: COLORS.bg,
    },
    calendarDayText:     { fontSize: 13, fontWeight: "600", color: COLORS.text },
    calendarDaySelected: { backgroundColor: COLORS.primary },
    calendarDaySelectedText: { color: "#fff", fontWeight: "700" },
    calendarDayToday:    { borderWidth: 1.5, borderColor: COLORS.primary },
    calendarDayDisabled: { opacity: 0.3 },

    timeSlotRow: { flexDirection: "row", flexWrap: "wrap", gap: 8, marginTop: 8 },
    timeSlot: {
        paddingHorizontal: 14,
        paddingVertical: 8,
        borderRadius: 10,
        borderWidth: 1.5,
        borderColor: COLORS.border,
        backgroundColor: "#fff",
    },
    timeSlotSelected: { backgroundColor: COLORS.primary, borderColor: COLORS.primary },
    timeSlotText:     { fontSize: 13, fontWeight: "600", color: COLORS.textMuted },
    timeSlotTextSelected: { color: "#fff" },
    timeSlotFull:     { opacity: 0.35 },

    bookForm: {
        backgroundColor: "#fff",
        margin: 16,
        borderRadius: 16,
        elevation: 3,
        padding: 20,
    },
    bookBtn: { borderRadius: 8, paddingVertical: 4, marginBottom: 10 },

    datePickerBtn: {
        borderWidth: 1.5,
        borderColor: COLORS.primary,
        borderRadius: 8,
        padding: 14,
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
        gap: 10,
        backgroundColor: COLORS.primaryPale,
    },
    datePickerBtnText: { flex: 1, fontSize: 14, color: COLORS.text, fontWeight: "600" },

    scheduleItem: {
        flexDirection: "row",
        alignItems: "center",
        backgroundColor: "#fff",
        borderRadius: 12,
        padding: 12,
        marginBottom: 8,
        elevation: 1,
        gap: 10,
    },
    scheduleTimebox: {
        backgroundColor: COLORS.primaryPale,
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 6,
        alignItems: "center",
    },

    emptyWrap:   { alignItems: "center", marginTop: 60, paddingHorizontal: 32 },
    emptyText:   { color: COLORS.textMuted, marginTop: 12, fontSize: 14, textAlign: "center" },
    emptySubtext:{ color: COLORS.textLight, fontSize: 12, marginTop: 4, textAlign: "center" },

    loadingWrap: { flex: 1, alignItems: "center", justifyContent: "center", backgroundColor: COLORS.bg },
});

export default Styles;
